from typing import Annotated, Sequence
from datetime import date, timedelta, datetime
from typing_extensions import TypedDict, Optional
from langchain_openai import ChatOpenAI
from tradingagents.agents import *
from langgraph.prebuilt import ToolNode
from langgraph.graph import END, StateGraph, START, MessagesState


# Researcher team state
class InvestDebateState(TypedDict):
    bull_history: Annotated[
        str, "Bullish Conversation history"
    ]  # Bullish Conversation history
    bear_history: Annotated[
        str, "Bearish Conversation history"
    ]  # Bullish Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    current_response: Annotated[str, "Latest response"]  # Last response
    judge_decision: Annotated[str, "Final judge decision"]  # Last response
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


# Risk management team state
class RiskDebateState(TypedDict):
    risky_history: Annotated[
        str, "Risky Agent's Conversation history"
    ]  # Conversation history
    safe_history: Annotated[
        str, "Safe Agent's Conversation history"
    ]  # Conversation history
    neutral_history: Annotated[
        str, "Neutral Agent's Conversation history"
    ]  # Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    latest_speaker: Annotated[str, "Analyst that spoke last"]
    current_risky_response: Annotated[
        str, "Latest response by the risky analyst"
    ]  # Last response
    current_safe_response: Annotated[
        str, "Latest response by the safe analyst"
    ]  # Last response
    current_neutral_response: Annotated[
        str, "Latest response by the neutral analyst"
    ]  # Last response
    judge_decision: Annotated[str, "Judge's decision"]
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


class AgentState(MessagesState):
    company_of_interest: Annotated[str, "Company that we are interested in trading"]
    trade_date: Annotated[str, "What date we are trading at"]

    sender: Annotated[str, "Agent that sent this message"]

    # research step
    market_report: Annotated[str, "Report from the Market Analyst"]
    sentiment_report: Annotated[str, "Report from the Social Media Analyst"]
    news_report: Annotated[
        str, "Report from the News Researcher of current world affairs"
    ]
    fundamentals_report: Annotated[str, "Report from the Fundamentals Researcher"]
    options_report: Annotated[str, "Report from the Options Analyst"]
    crypto_report: Annotated[str, "Report from the Crypto Analyst"]
    macro_report: Annotated[str, "Report from the Macro Analyst"]

    # coach reports (from Discord daily plans)
    coach_d_plan: Annotated[str, "Daily plan from Coach D via Discord"]
    coach_i_plan: Annotated[str, "Daily plan from Coach I via Discord"]
    coach_s_plan: Annotated[str, "Daily plan from Coach S via Discord"]
    coach_n_plan: Annotated[str, "Daily plan from Coach N via Discord"]
    
    coach_d_charts: Annotated[list, "Chart URLs from Coach D"]
    coach_i_charts: Annotated[list, "Chart URLs from Coach I"]
    coach_s_charts: Annotated[list, "Chart URLs from Coach S"]
    coach_n_charts: Annotated[list, "Chart URLs from Coach N"]
    
    coach_d_report: Annotated[str, "Report from Coach D"]
    coach_i_report: Annotated[str, "Report from Coach I"]
    coach_s_report: Annotated[str, "Report from Coach S"]
    coach_n_report: Annotated[str, "Report from Coach N"]

    # researcher team discussion step
    investment_debate_state: Annotated[
        InvestDebateState, "Current state of the debate on if to invest or not"
    ]
    investment_plan: Annotated[str, "Plan generated by the Analyst"]

    trader_investment_plan: Annotated[str, "Plan generated by the Trader"]

    # risk management quantitative metrics
    risk_metrics: Annotated[dict, "Quantitative risk assessment metrics from RiskCalculator"]
    account_balance: Annotated[float, "Current account balance for position sizing"]
    existing_positions: Annotated[list, "List of existing portfolio positions for risk assessment"]

    # risk management team discussion step
    risk_debate_state: Annotated[
        RiskDebateState, "Current state of the debate on evaluating risk"
    ]
    final_trade_decision: Annotated[str, "Final decision made by the Risk Analysts"]
